"use client";

import { FormEvent, useEffect, useState } from "react";
import PageShell from "@/components/PageShell";
import { Address, CartView, checkout, createAddress, getAddresses, getCart, initializePayment } from "@/lib/savora-api";

export default function Page() {
  const [cart, setCart] = useState<CartView | null>(null); const [addresses, setAddresses] = useState<Address[]>([]); const [addressId, setAddressId] = useState(""); const [form, setForm] = useState({ fullAddress: "", city: "Lagos", state: "Lagos" }); const [error, setError] = useState(""); const token = typeof window !== "undefined" ? localStorage.getItem("savora.accessToken") : null;
  useEffect(() => { if (!token) return; Promise.all([getCart(token), getAddresses(token)]).then(([loadedCart, loadedAddresses]) => { setCart(loadedCart); setAddresses(loadedAddresses); setAddressId(loadedAddresses.find(address => address.isDefault)?.id || loadedAddresses[0]?.id || ""); }).catch(reason => setError(reason instanceof Error ? reason.message : "Could not load checkout")); }, [token]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!token) return; setError(""); try { let selected = addressId; if (!selected) { const address = await createAddress(token, { ...form, label: "Delivery", country: "Nigeria" }); selected = address.id; } const result = await checkout(token, { addressId: selected, paymentProvider: "KORAPAY" }); const payment = await initializePayment(token, result.parentCheckout.id, "KORAPAY"); window.location.href = payment.authorizationUrl; } catch (reason) { setError(reason instanceof Error ? reason.message : "Checkout failed"); } }
  if (!token) return <PageShell><section className="section container"><h1>Checkout</h1><p>Please sign in before checkout.</p></section></PageShell>;
  return <PageShell><section className="section container"><h1>Checkout</h1>{error && <p role="alert" style={{ color: "#b42318" }}>{error}</p>}<form onSubmit={submit}><div className="cart-grid" style={{ marginTop: 20 }}><div className="form-card"><h2>Delivery details</h2>{addresses.length > 0 && <><label htmlFor="address">Saved address</label><select id="address" value={addressId} onChange={event => setAddressId(event.target.value)}><option value="">Add a new address</option>{addresses.map(address => <option key={address.id} value={address.id}>{address.label || address.city}: {address.fullAddress}</option>)}</select></>} {!addressId && <><label htmlFor="fullAddress">Delivery address</label><textarea id="fullAddress" required value={form.fullAddress} onChange={event => setForm({ ...form, fullAddress: event.target.value })} placeholder="House number, street, area" /><label htmlFor="city">City</label><input id="city" required value={form.city} onChange={event => setForm({ ...form, city: event.target.value })} /><label htmlFor="state">State</label><input id="state" required value={form.state} onChange={event => setForm({ ...form, state: event.target.value })} /></>}</div><aside className="form-card summary"><h2>Order summary</h2><p className="row"><span>Subtotal</span><span>₦{Number(cart?.subtotal || 0).toLocaleString()}</span></p><hr /><h2 className="row"><span>Total</span><span className="price">₦{Number(cart?.subtotal || 0).toLocaleString()}</span></h2><button className="btn" disabled={!cart?.items.length} style={{ width: "100%", marginTop: 20 }}>Continue to payment</button></aside></div></form></section></PageShell>;
}
